# Change these first
owner: Rzzvaan-Muhammad # Your GitHub organization or username, where this repository lives
repo: Fake-Youtube-App # The name of this repository

sites:
  - name: Fake-Youtube-App
    url: https://rizwan-muhammad-youtube.netlify.app

notifications:
  - name: Slack Notification on Test Failure
    if: ${{ failure() }}
    uses: ravsamhq/notify-slack-action@v1
    with:
      status: ${{ job.status }}
      token: ${{ secrets.GH_PAT }}
      notify_when: 'failure'
      notification_title: "E2E {workflow} triggered by *${{ github.event.action }}* has {status_message}"
      message_format: "{emoji} *{workflow}* {status_message} | <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Test Result>"
      footer: "Linked Repo: <{repo_url}|{repo}>"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.NOTIFICATION_SLACK_WEBHOOK_URL }}

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: rizwan-muhammad-youtube.netlify.app
  baseUrl: /Fake-Youtube-App
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)


